version: '3.7'
services:
     vue-app:
          build: ./frontend
          ports:
             - "8080:8080"
          volumes:
             - .:/code
          depends_on:
             - backend
     backend:
          build: ./backend
          ports:
             - "3000:3000"