services:
  - type: web
    name: frontend
    env: docker
    dockerContext: ./frontend
    rootDir: frontend
  
  - type: web
    name: backend
    env: docker
    dockerContext: ./backend
    rootDir: backend
